### ISSUE TITLE
proposal: add support for ?0 to generate a random float between 0 and 1

### ISSUE THREAD

**Issue by fzipp** [robpike/ivy#167]
Some APL dialects (including Dyalog APL and J) feature a unary roll operator that generates a random floating-point number between 0 and 1 when the operand is zero. See https://aplwiki.com/wiki/Roll

Example:

```
?0
	0.945196149294
```

The revised doc text could be:

```
Roll              ?B    ?       One integer selected randomly from the first B integers
                                If B=0, random floating-point number between 0 and 1
```

The implementation would return

	BigFloat{big.NewFloat(c.Config().Random().Float64())}

Is this something you could imagine for Ivy as well? If so, I can create a pull request.

**Comment by robpike** [comment]
That's pretty hacky but I suppose precedence makes it acceptable.

**Comment by rsc** [comment]
What about ?1.0 doing that, and similarly ?10.0 generates a random float in [0, 10.0)?

**Comment by robpike** [comment]
I like the ?float idea much better.
I wonder what we can do with ?3j2....

**Comment by robpike** [comment]
Also should bump the rand version to v2.

I'll take care of this.

**Comment by robpike** [comment]
Because numbers get "shrunk" as soon as they are scanned (1.0 becomes an integer in the parser, 0.5 becomes a rational, etc.), using the type to choose the roll result only works if you force it: ?float 1. That's ugly, but can work. Also, if you write ?f where f is a variable holding a float, it could cause trouble if halfway through the calculation f unexpectedly becomes an integer. This is a bug waiting to happen.

Because ?0 is also ugly (at least to me), and ?float 1 hardly better, the answer may be instead to provide a different operator for the float variant. I'll think about it.
