### ISSUE TITLE
Inconsistent order of operations?

### ISSUE THREAD

**Issue by mpl** [robpike/ivy#21]
Given that "binary operators apply to the operand immediately to the left and to everything to the right", I was expecting:

    (2/3**2) == (2/(3**2)) , and not (2/3**2) == ((2/3)**2)) as it seems to be.

And fwiw, if one replaces division with multiplication, one gets as expected:

    (2*3**2) == (2*(3**2)) ( and not (2*3**2) == ((2*3)**2) )

I did not find any explanation for this behavior either on https://godoc.org/robpike.io/ivy or on https://en.wikipedia.org/wiki/APL_syntax_and_symbols.

What am I missing please?

**Comment by robpike** [comment]
2/3**2 is (2/3) ** 2 because the the scanner is greedy about grabbing fractions. 2/3 is one number: two-thirds, not literally two divided by three.

You are correct however that this is not explained well in the documentation. I will fix that in the next release.

**Comment by mpl** [comment]
I see, thanks.
I understand the merit and convenience of being able to represent fractional numbers, but it's a bit unfortunate that the behaviour in effect looks like an exception to an otherwise beautifully simple rule.

I suppose it's just a matter of getting used to it once documented.

**Comment by benjamin-rood** [comment]
Two cents:
When the given expression is written as `(2/3) ** 2` then the logical result:

![screen shot 2016-01-27 at 11 51 33 am](https://cloud.githubusercontent.com/assets/10102132/12597948/65d75278-c4ec-11e5-95f8-2b6a1f00c15f.png)

Will always be sensible. Perhaps the thing to do (in the documentation) is to emphasise the use of brackets, rather than making assumptions. Maybe I'm crazy (or just bad at math) but I always group operations when there is any chance of any ambiguity, whether on a Casio or when coding.

**Comment by robpike** [comment]
Fixed in the dev branch.
